#######################################################################################
# Book settings
title                         : Programming for Quantitative Economics
author                        : Thomas J. Sargent and John Stachurski
logo                          : 'qe-logo-large.png'
email                         : admin@quantecon.org
description: >-
  This book presents a set of lectures on Python programming for quantitative economics, designed and written by **Thomas J. Sargent** and **John Stachurski**.


execute:
  execute_notebooks           : cache


html:
  favicon                     : 'qe-logo-large.png'
  home_page_in_navbar         : false
  use_edit_page_button        : true
  use_repository_button       : true
  use_issue_button            : true


repository:
  url                         : https://github.com/executablebooks/quantecon-example/
  branch                      : master
  path_to_book                : book


# launch_buttons:
  # notebook_interface          : classic
  # binderhub_url               : "https://mybinder.org"
  # colab_url                   : "https://colab.research.google.com"
  # thebe                       : true
